import { Router, type RequestHandler } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma'
import { requireAuth } from '../middleware/auth'
import { requireRole } from '../middleware/roles'

const router = Router()
const querySchema = z.object({ sport: z.string().trim().optional(), leagueId: z.coerce.number().int().positive().optional(), teamId: z.coerce.number().int().positive().optional(), date: z.string().optional(), status: z.enum(['SCHEDULED','LIVE','FINISHED','POSTPONED','CANCELLED']).optional(), from: z.coerce.date().optional(), to: z.coerce.date().optional(), search: z.string().trim().max(100).optional(), page: z.coerce.number().int().positive().default(1), limit: z.coerce.number().int().positive().max(100).default(50) })
const createSchema = z.object({ leagueId:z.number().int().positive(), homeTeamId:z.number().int().positive(), awayTeamId:z.number().int().positive(), externalId:z.string().trim().max(100).optional(), kickoffAt:z.coerce.date(), status:z.enum(['SCHEDULED','LIVE','FINISHED','POSTPONED','CANCELLED']).default('SCHEDULED'), homeScore:z.number().int().min(0).optional(), awayScore:z.number().int().min(0).optional(), venue:z.string().trim().max(200).optional() }).refine(v=>v.homeTeamId!==v.awayTeamId,{message:'Home and away teams must differ.'})

const listHandler: RequestHandler = async (req,res,next)=>{ try { const q=querySchema.safeParse(req.query); if(!q.success){res.status(400).json({success:false,error:{code:'VALIDATION_ERROR',message:'Invalid fixture filters.',details:q.error.flatten().fieldErrors}});return}; const {page,limit,date,...f}=q.data; let from=f.from; let to=f.to; if(date){const d=new Date(date); if(Number.isNaN(d.getTime())){res.status(400).json({success:false,error:{code:'VALIDATION_ERROR',message:'Invalid date.'}});return}; from=new Date(d); to=new Date(d); to.setDate(to.getDate()+1)} const where:any={...(f.leagueId?{leagueId:f.leagueId}:{}),...(f.teamId?{OR:[{homeTeamId:f.teamId},{awayTeamId:f.teamId}]}:{}),...(f.status?{status:f.status}:{}),...(from||to?{kickoffAt:{...(from?{gte:from}:{}),...(to?{lt:to}:{})}}:{}),...(f.search?{OR:[{homeTeam:{name:{contains:f.search}}},{awayTeam:{name:{contains:f.search}}}]}:{})}; const [fixtures,total]=await Promise.all([prisma.fixture.findMany({where,include:{league:{include:{sport:true}},homeTeam:true,awayTeam:true},orderBy:{kickoffAt:'asc'},skip:(page-1)*limit,take:limit}),prisma.fixture.count({where})]); res.json({success:true,data:{fixtures,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}}}) }catch(e){next(e)} }
router.get('/',listHandler)
router.get('/live',async(_req,res,next)=>{try{const fixtures=await prisma.fixture.findMany({where:{status:'LIVE'},include:{league:true,homeTeam:true,awayTeam:true},orderBy:{kickoffAt:'asc'}});res.json({success:true,data:{fixtures}})}catch(e){next(e)}})
router.get('/today',async(_req,res,next)=>{const now=new Date();const from=new Date(now);from.setHours(0,0,0,0);const to=new Date(from);to.setDate(to.getDate()+1);try{const fixtures=await prisma.fixture.findMany({where:{kickoffAt:{gte:from,lt:to}},include:{league:true,homeTeam:true,awayTeam:true},orderBy:{kickoffAt:'asc'}});res.json({success:true,data:{fixtures}})}catch(e){next(e)}})
router.get('/upcoming',async(_req,res,next)=>{try{const fixtures=await prisma.fixture.findMany({where:{kickoffAt:{gte:new Date()},status:'SCHEDULED'},include:{league:true,homeTeam:true,awayTeam:true},orderBy:{kickoffAt:'asc'},take:100});res.json({success:true,data:{fixtures}})}catch(e){next(e)}})
router.get('/:id',async(req,res,next)=>{try{const fixture=await prisma.fixture.findUnique({where:{id:Number(req.params.id)},include:{league:{include:{sport:true}},homeTeam:true,awayTeam:true}});if(!fixture){res.status(404).json({success:false,error:{code:'FIXTURE_NOT_FOUND',message:'Fixture not found.'}});return}res.json({success:true,data:{fixture}})}catch(e){next(e)}})
router.post('/',requireAuth,requireRole('ADMIN'),async(req,res,next)=>{try{const p=createSchema.safeParse(req.body);if(!p.success){res.status(400).json({success:false,error:{code:'VALIDATION_ERROR',message:'Invalid fixture details.',details:p.error.flatten().fieldErrors}});return}const fixture=await prisma.fixture.create({data:p.data});res.status(201).json({success:true,data:{fixture}})}catch(e){next(e)}})
export default router
